### ISSUE TITLE
missing file: `conf/assembly.asm`

### ISSUE THREAD

**Issue by junxian-li-hpc** [tubs-eis/VLIW-Retargetable-Compiler-Backend#1]
I noticed that the file `conf/assembly.asm` is missing from the repository. The `compile_example.sh` script references this file, but it cannot be found.

Could you please check and provide the missing `assembly.asm` file in the conf directory?

Thank you for your attention to this matter. I appreciate your prompt response.

**Comment by F-Stuckmann** [comment]
Thanks for the hint. 
I provided an example assembly file with virtual registers (VxRn) and physical Registers (V0Rn). 
Virtual register will be allocated by the compiler, while physical register are used to transfer data between BBs and are unchanged.
